name: Create Draft Branch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: 'draft-release-branch1'
      - name: Create new branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'draft-release-branch1'
      - name: Checkout CLI Repo with draft-release-branch1
        uses: actions/checkout@v2
        with:
          ref: draft-release-branch1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 
      - name: Execute py script 
        run: |
          python3 .github/scripts/draft-release/draft.py      
      - name: Commit and push changes
        run: |
          git config --global user.email "sraghav@twilio.com"
          git config --global user.name "sr010"
          git add -A
          git commit -m "Draft specific changes from the script"
          git push   