name: NPM Download Metrics

on:
  workflow_dispatch:
  schedule:
    # - cron: "0 0 * * *" #runs at 00:00 UTC everyday
    - cron: "*/5 * * * *" #runs at 00:00 UTC everyday   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Run a one-line script
      #   uses: masci/datadog@v1
      #   with:
      #     api-key: ${{ secrets.DATADOG_API_KEY }}
      #     metrics: |
      #       - type: "count"
      #         name: "downloads.npm_release1.count"
      #         value: 958
      #         host: ${{ github.repository_owner }}
      #         tags:
      #           - "project:${{ github.repository }}"
      - name: Checkout cli repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: Execute py script # run the run.py to get the latest data
        env:
          DD_SITE: datadoghq.com
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}   
        run: |
          pip3 install datadog-api-client
          pip3 install requests
          pip3 install datetime
          python3 .github/scripts/datadog.py